// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsScraper_Web.Models;

#nullable disable

namespace NewsScraper_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1");

            modelBuilder.Entity("NewsScraper_Web.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeBusiness")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeEntertainment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludePolitics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeScience")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeUs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeWorld")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KindleEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("NewsScraper_Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewsScraper_Web.Models.Settings", b =>
                {
                    b.HasOne("NewsScraper_Web.Models.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("NewsScraper_Web.Models.Settings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsScraper_Web.Models.User", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
